[admin_users]
gholape = "gholape"
naveen = "naveen"

[firebase]
type = "service_account"
project_id = "gholapevan"
private_key_id = "9fde02e592cb1230a2cad908eac64be83ef56f3e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYnniV7XvFz423
EqjfVC8/I0GX9Jb/j4xOF19NyhamPdFbTi235ONyVgOqK5ekBDkWpNi4TUzr3wH7
GPJg8L8UXnTjw5znH0tfWzn6q5Lf8rYfvKLCPGifx6wvQE/9te00PcAUaSIIRrxa
TFR+2UUcPr5A/cpwzLQqL6BgNKKzIO/d0mQIAdoKud/nUyNvmjr/P4cU65eu1vq4
VxlcHE+tCl/x8sO/eaFmllCZy3mgVKmIlDgJPdSHCaJrLe14C9uypZf5nLfbyaTu
+giCrpNdwYtHT0Huk+YZ3cPuDnuhlDR3TGcU7hXBGjOrWR2qq4KZScWCWzqK34CP
SfLi1oI7AgMBAAECggEAPOqf6gPw79swzv5hLkbtVs+tOkhTzuzOjUrx7Nw5XyB0
hHO3dtui1zuy2cTtkXdoC/w/Toz4I3uPUFi8QepF8ozjLhghc/T/Qi/o+/9or/+y
JwfFlS7EeeYaeX+7jeKEK+Jr3Rm7jj8hpg8qeLkjRytaCBnkqFJkpSP+aPgJauKf
z5yWYNnS7XXrp9cZysHL0xgJ7yCrUtedbYbUNE4vKt491seffgSZU8M90B7L+wQp
JuTipb2IMgub0OCN6D+dc73hq0IR8oknWvzdFbeHaQPCZS5aBu/p15hkMU+UMAHH
Q9jY7+hbk9ql92HVY7rdCR5VGfidbROavJpodk1fHQKBgQDXHppEJ4b214ixUmbU
5aj2VABaXAfvRDi38CBnRbicaPUF4+HNUKPN1U7NOfc6yugcwZkZatJ9EMzm9SZM
efhhsJ3ffR85hbrMOQg6pv/KadGJaqq9HIu8C83dx0RPtVlAYHKUB7dGn7FF+qCT
AoTPi7/xCG3+uOS93LNX1L8pTwKBgQC1n0Rvn2rdQbyAWGfhKpd+9Vd26Xkr6F7P
+G8gkN0WWUqoIuMsgcBsxYJajmRjxQ4Cv35wc8cdeKMIJy5o87oFbD6ebaqNq6oT
eOsxUUaxz/Ivhrg/EbuWTaIEsrWf9dxLvGIoQ9gk/YBC4GXRkbQQDxsD7tMBwo5D
r7vvhSzFVQKBgQCVj1U5pTGUVG1Yuy17PuClweks6Wcq1oeIeo5MvpCHTgFsQu8u
S65W4MKUtIRKf9+4fnDu1vHYueF7gV1LNlGVubFJPDiFSZCBg/VQseKM290uaNaj
/EC6UIqkcnHv6OlQdL20ZVjq5QPe30zcaJflpAeikHXI7ss5pUObAPKWyQKBgEiO
IKPK9sD/EtPe/Vi5UB4a2t8ZNBvzT3UblSFYXcogz69NiJ1uFDYfzQxqF/a3cPpu
D4/S4LeISvDl3id1PloOPRHDU8AW1PHEe4iPJIPCQ8jys8YWSm8oAlKIJgCKEoB6
+GeHeuCEGOoehO5sm5dSwYMXtFnepECsApMUC6elAoGBALfVSiqu6Z1340oWRjLM
9ieBtUo+wigkvvJGRfyMXTniVoQ+Uj0N2SfwSBQQ5CwfjMl8XQ/8LYuGm/2CnNlp
64wjTmPZhVsHS4xKCESKN6N9ptw4aXcIvJHeacgy2iV0MsoVW2fYQN1J7btUSY6s
4qxftEFxhl3CCSzVzQh12arc
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@gholapevan.iam.gserviceaccount.com"
client_id = "111403705278838807669"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40gholapevan.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
